spring.application.name=PractiseProject1

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/finishers
spring.datasource.username=root
spring.datasource.password=ankit123
